#!/bin/sh -e

. /etc/cross-shell/config

if [ $# -ne 1 ]; then
    echo "Usage: sc-bootstrap-target <arch>"
    exit 1
fi

ARCH="$1"

HOSTARCH=$(dpkg --print-architecture)
if [ -z "$HOSTARCH" ]; then
    echo "ERROR: can't detect host architecture"
    exit 1
fi

if [ ! -d "/rootfs-$HOSTARCH" ]; then
    echo "ERROR: /rootfs-$HOSTARCH does not exist, unable to perform a cross-bootstrap."
    echo "ERROR: run sc-bootstrap-host before."
    exit 1
fi

ROOTFS=/rootfs-$ARCH

if [ -e "$ROOTFS" ]; then
    echo "ERROR: $ROOTFS already exists. Delete it before running sc-bootstrap-target."
    exit 1
fi

echo "=== bootstrap target ==="

$ROOT_CMD mkdir -p $ROOTFS
$ROOT_CMD chown -R $UID:$UID $ROOTFS

cross-bs $ARCH

echo "deb $REPO $SUITE core security gui media" > $ROOTFS/etc/apt/sources.list
echo "APT::Architecture \"$ARCH\";" > $ROOTFS/etc/apt/apt.conf
if [ -n "$http_proxy" ]; then
    echo "Acquire::http::Proxy \"$http_proxy\";" >> $ROOTFS/etc/apt/apt.conf
fi
if [ -n "$ftp_proxy" ]; then
    echo "Acquire::ftp::Proxy \"$ftp_proxy\";" >> $ROOTFS/etc/apt/apt.conf
fi
echo oi > $ROOTFS/etc/hostname

cross-shell $ARCH apt-get update
