#!/bin/sh -e

. /etc/cross-shell/config

if [ $# -ne 0 ]; then
    echo "Usage: sc-bootstrap-host"
    exit 1
fi

# for debootstrap
PATH=$PATH:/usr/sbin

HOSTARCH=`dpkg --print-architecture`
if [ -z "$HOSTARCH" ]; then
    echo "ERROR: can't detect host architecture"
    exit 1
fi

ROOTFS="/rootfs-$HOSTARCH"
if [ -e "$ROOTFS" ]; then
    echo "ERROR: $ROOTFS already exists. Delete it before running sc-bootstrap-host."
    exit 1
fi

echo "=== bootstrap host ==="

$ROOT_CMD mkdir -p $ROOTFS

cross-bs $HOSTARCH

# suid ldconfig binary, otherwise we won't be able to run it as build user
# inside chroot.
$ROOT_CMD chmod u+s $ROOTFS/sbin/ldconfig
